#!/bin/sh

# Remove config and Makevars
rm -fv config.* src/Makevars *Zone.Identifier

# Remove Autoconf cache, backup, and compiled files
rm -rfv autom4te.cache *~ */*~ src/*.o src/*.so src/*.dll src/*.dylib src/*.a
