// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cxxfit
List cxxfit(NumericVector tht, NumericMatrix revents, NumericMatrix rpoly, NumericVector tperiod, double rinteg0, NumericMatrix ihess, int ndiv, double eps, bool verbose, int nthreads);
RcppExport SEXP ETAS_cxxfit(SEXP thtSEXP, SEXP reventsSEXP, SEXP rpolySEXP, SEXP tperiodSEXP, SEXP rinteg0SEXP, SEXP ihessSEXP, SEXP ndivSEXP, SEXP epsSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tht(thtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type revents(reventsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rpoly(rpolySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tperiod(tperiodSEXP);
    Rcpp::traits::input_parameter< double >::type rinteg0(rinteg0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ihess(ihessSEXP);
    Rcpp::traits::input_parameter< int >::type ndiv(ndivSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cxxfit(tht, revents, rpoly, tperiod, rinteg0, ihess, ndiv, eps, verbose, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// cxxdeclust
List cxxdeclust(NumericVector param, NumericMatrix revents, NumericMatrix rpoly, NumericVector bwd, NumericVector tperiod, int ndiv);
RcppExport SEXP ETAS_cxxdeclust(SEXP paramSEXP, SEXP reventsSEXP, SEXP rpolySEXP, SEXP bwdSEXP, SEXP tperiodSEXP, SEXP ndivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type revents(reventsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rpoly(rpolySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bwd(bwdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tperiod(tperiodSEXP);
    Rcpp::traits::input_parameter< int >::type ndiv(ndivSEXP);
    rcpp_result_gen = Rcpp::wrap(cxxdeclust(param, revents, rpoly, bwd, tperiod, ndiv));
    return rcpp_result_gen;
END_RCPP
}
// cxxrates
List cxxrates(NumericVector param, NumericMatrix revents, NumericVector bwd, NumericVector tperiod, NumericVector gx, NumericVector gy);
RcppExport SEXP ETAS_cxxrates(SEXP paramSEXP, SEXP reventsSEXP, SEXP bwdSEXP, SEXP tperiodSEXP, SEXP gxSEXP, SEXP gySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type revents(reventsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bwd(bwdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tperiod(tperiodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gx(gxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gy(gySEXP);
    rcpp_result_gen = Rcpp::wrap(cxxrates(param, revents, bwd, tperiod, gx, gy));
    return rcpp_result_gen;
END_RCPP
}
// cxxtimetrans
NumericVector cxxtimetrans(NumericVector theta, NumericMatrix revents, NumericMatrix rpoly, NumericVector tperiod, double integ0, int ndiv);
RcppExport SEXP ETAS_cxxtimetrans(SEXP thetaSEXP, SEXP reventsSEXP, SEXP rpolySEXP, SEXP tperiodSEXP, SEXP integ0SEXP, SEXP ndivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type revents(reventsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rpoly(rpolySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tperiod(tperiodSEXP);
    Rcpp::traits::input_parameter< double >::type integ0(integ0SEXP);
    Rcpp::traits::input_parameter< int >::type ndiv(ndivSEXP);
    rcpp_result_gen = Rcpp::wrap(cxxtimetrans(theta, revents, rpoly, tperiod, integ0, ndiv));
    return rcpp_result_gen;
END_RCPP
}
// cxxlambdtemp
NumericVector cxxlambdtemp(NumericVector tg, NumericVector theta, NumericMatrix revents, NumericMatrix rpoly, NumericVector tperiod, double integ0, int ndiv);
RcppExport SEXP ETAS_cxxlambdtemp(SEXP tgSEXP, SEXP thetaSEXP, SEXP reventsSEXP, SEXP rpolySEXP, SEXP tperiodSEXP, SEXP integ0SEXP, SEXP ndivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tg(tgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type revents(reventsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rpoly(rpolySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tperiod(tperiodSEXP);
    Rcpp::traits::input_parameter< double >::type integ0(integ0SEXP);
    Rcpp::traits::input_parameter< int >::type ndiv(ndivSEXP);
    rcpp_result_gen = Rcpp::wrap(cxxlambdtemp(tg, theta, revents, rpoly, tperiod, integ0, ndiv));
    return rcpp_result_gen;
END_RCPP
}
// cxxlambspat
NumericVector cxxlambspat(NumericVector xg, NumericVector yg, NumericVector theta, NumericMatrix revents, NumericMatrix rpoly, NumericVector tperiod, NumericVector bwd);
RcppExport SEXP ETAS_cxxlambspat(SEXP xgSEXP, SEXP ygSEXP, SEXP thetaSEXP, SEXP reventsSEXP, SEXP rpolySEXP, SEXP tperiodSEXP, SEXP bwdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xg(xgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yg(ygSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type revents(reventsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rpoly(rpolySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tperiod(tperiodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bwd(bwdSEXP);
    rcpp_result_gen = Rcpp::wrap(cxxlambspat(xg, yg, theta, revents, rpoly, tperiod, bwd));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP cdeclust(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP cfit(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP clambdax(SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"ETAS_cxxfit", (DL_FUNC) &ETAS_cxxfit, 10},
    {"ETAS_cxxdeclust", (DL_FUNC) &ETAS_cxxdeclust, 6},
    {"ETAS_cxxrates", (DL_FUNC) &ETAS_cxxrates, 6},
    {"ETAS_cxxtimetrans", (DL_FUNC) &ETAS_cxxtimetrans, 6},
    {"ETAS_cxxlambdtemp", (DL_FUNC) &ETAS_cxxlambdtemp, 7},
    {"ETAS_cxxlambspat", (DL_FUNC) &ETAS_cxxlambspat, 7},
    {"cdeclust",          (DL_FUNC) &cdeclust,           5},
    {"cfit",              (DL_FUNC) &cfit,               4},
    {"clambdax",          (DL_FUNC) &clambdax,           5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ETAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
