# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxxfit <- function(tht, revents, rpoly, tperiod, rinteg0, ihess, ndiv, eps, verbose, nthreads, mver) {
    .Call(`_ETAS_cxxfit`, tht, revents, rpoly, tperiod, rinteg0, ihess, ndiv, eps, verbose, nthreads, mver)
}

cxxdeclust <- function(param, revents, rpoly, bwd, tperiod, ndiv, mver) {
    .Call(`_ETAS_cxxdeclust`, param, revents, rpoly, bwd, tperiod, ndiv, mver)
}

cxxrates <- function(param, revents, bwd, tperiod, gx, gy, mver) {
    .Call(`_ETAS_cxxrates`, param, revents, bwd, tperiod, gx, gy, mver)
}

cxxtimetrans <- function(theta, revents, rpoly, tperiod, integ0, ndiv, mver) {
    .Call(`_ETAS_cxxtimetrans`, theta, revents, rpoly, tperiod, integ0, ndiv, mver)
}

cxxlambdtemp <- function(tg, theta, revents, rpoly, tperiod, integ0, ndiv, mver) {
    .Call(`_ETAS_cxxlambdtemp`, tg, theta, revents, rpoly, tperiod, integ0, ndiv, mver)
}

cxxlambspat <- function(xg, yg, theta, revents, rpoly, tperiod, bwd, mver) {
    .Call(`_ETAS_cxxlambspat`, xg, yg, theta, revents, rpoly, tperiod, bwd, mver)
}

cxxSmooth <- function(x, y, bwd, gx, gy, expand) {
    .Call(`_ETAS_cxxSmooth`, x, y, bwd, gx, gy, expand)
}

cxxstpoisstest <- function(xrank, yrank, M) {
    .Call(`_ETAS_cxxstpoisstest`, xrank, yrank, M)
}

cxxstpoisstestMP <- function(xrank, yrank, M, nthreads) {
    .Call(`_ETAS_cxxstpoisstestMP`, xrank, yrank, M, nthreads)
}

