# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxxfit <- function(tht, revents, rpoly, tperiod, rinteg0, ihess, ndiv, eps, verbose, nthreads) {
    .Call('_ETAS_cxxfit', PACKAGE = 'ETAS', tht, revents, rpoly, tperiod, rinteg0, ihess, ndiv, eps, verbose, nthreads)
}

cxxdeclust <- function(param, revents, rpoly, bwd, tperiod, ndiv) {
    .Call('_ETAS_cxxdeclust', PACKAGE = 'ETAS', param, revents, rpoly, bwd, tperiod, ndiv)
}

cxxrates <- function(param, revents, bwd, tperiod, gx, gy) {
    .Call('_ETAS_cxxrates', PACKAGE = 'ETAS', param, revents, bwd, tperiod, gx, gy)
}

cxxtimetrans <- function(theta, revents, rpoly, tperiod, integ0, ndiv) {
    .Call('_ETAS_cxxtimetrans', PACKAGE = 'ETAS', theta, revents, rpoly, tperiod, integ0, ndiv)
}

cxxlambdtemp <- function(tg, theta, revents, rpoly, tperiod, integ0, ndiv) {
    .Call('_ETAS_cxxlambdtemp', PACKAGE = 'ETAS', tg, theta, revents, rpoly, tperiod, integ0, ndiv)
}

cxxlambspat <- function(xg, yg, theta, revents, rpoly, tperiod, bwd) {
    .Call('_ETAS_cxxlambspat', PACKAGE = 'ETAS', xg, yg, theta, revents, rpoly, tperiod, bwd)
}

cxxSmooth <- function(x, y, bwd, gx, gy, expand) {
    .Call('_ETAS_cxxSmooth', PACKAGE = 'ETAS', x, y, bwd, gx, gy, expand)
}

cxxstpoisstest <- function(xrank, yrank, M) {
    .Call('_ETAS_cxxstpoisstest', PACKAGE = 'ETAS', xrank, yrank, M)
}

cxxstpoisstestMP <- function(xrank, yrank, M, nthreads) {
    .Call('_ETAS_cxxstpoisstestMP', PACKAGE = 'ETAS', xrank, yrank, M, nthreads)
}

