# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxxfit <- function(tht, revents, rpoly, tperiod, rinteg0, ihess, ndiv, eps, verbose, nthreads) {
    .Call('ETAS_cxxfit', PACKAGE = 'ETAS', tht, revents, rpoly, tperiod, rinteg0, ihess, ndiv, eps, verbose, nthreads)
}

cxxdeclust <- function(param, revents, rpoly, bwd, tperiod, ndiv) {
    .Call('ETAS_cxxdeclust', PACKAGE = 'ETAS', param, revents, rpoly, bwd, tperiod, ndiv)
}

cxxtimetrans <- function(theta, revents, rpoly, tperiod, integ0, ndiv) {
    .Call('ETAS_cxxtimetrans', PACKAGE = 'ETAS', theta, revents, rpoly, tperiod, integ0, ndiv)
}

cxxlambdtemp <- function(tg, theta, revents, rpoly, tperiod, integ0, ndiv) {
    .Call('ETAS_cxxlambdtemp', PACKAGE = 'ETAS', tg, theta, revents, rpoly, tperiod, integ0, ndiv)
}

cxxlambspat <- function(xg, yg, theta, revents, rpoly, tperiod, bwd) {
    .Call('ETAS_cxxlambspat', PACKAGE = 'ETAS', xg, yg, theta, revents, rpoly, tperiod, bwd)
}

maxnumthread <- function() {
    .Call('ETAS_maxnumthread', PACKAGE = 'ETAS')
}

